[package]
name = "bebion-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
bebion-compiler = { path = "../bebion-compiler" }
bebion-gc = { path = "../bebion-gc" }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
tracing = "0.1"
serde_json = "1.0"